### ISSUE TITLE
Ecrypted Code Found

### ISSUE THREAD

**Issue by imskaaz** [Jefreesujit/easyminer#6]
Encrypted code found, are this including hidden fees ?

**Comment by Jefreesujit** [comment]
Hi @imskaaz, 
Github uses trackers to find and prevent cryptojacking, if it finds any browser based mining code, it requests the users to take it down. So the encyrpted code is basically to mask the crypto mining code from the github trackers. And its just a base64 string, If you want just try to convert the base64 string to normal using `atob()`, you can see the actual code.

And to answer your question, no i don't take any fees as i built it for learning purpose. All i built is just a client, and the request would directly point to the mining pool and the address you specify, so there is no way i can take a cut out of it. :)
